export const ADD_QUESTION="ADD_QUESTION"
export const ADD_OPTION="ADD_OPTION"
export const DELETE_QUESTION="DELETE_QUESTION"
export const DELETE_OPTION="DELETE_OPTION"
export const MODIFY_QUESTION="MODIFY_QUESTION"
export const MODIFY_OPTION= "MODIFY_OPTION"
export const MODIFY_TITLE= "MODIFY_TITLE"
export const MODIFY_DESCRIPTION= "MODIFY_DESCRIPTION"



    
